test_that("unibiv matches MATLAB reference on FSM_Y dataset", {
  skip_if_not(nzchar(Sys.getenv("FSDA_DEV_VENV")), "MATLAB engine not available")
  Y_path   <- system.file("extdata/FSM/FSM_Y.csv", package = "fsdabridge")
  ref_path <- system.file("extdata/unibiv/fre_MATLAB.csv", package = "fsdabridge")
  skip_if(Y_path == "" || ref_path == "", "fixture/reference not found")
  Y   <- as.matrix(read.csv(Y_path))
  ref <- as.matrix(read.csv(ref_path))
  h <- start_engine("unibiv")
  on.exit(stop_engine(h), add = TRUE)
  fre <- unibiv(h, Y)
  expect_equal(dim(fre), dim(ref))
  max_diff <- max(abs(as.numeric(fre) - as.numeric(ref)))
  expect_lt(max_diff, 1e-9)
})
